kind: pipeline
name: default

type: docker
steps:
  - name: linter
    image: golang
    commands:
      - go fmt ./...
  - name: api_server_test
    image: golang
    commands:
      - cd cmd
      - go test
      - go build
  - name: db_test
    image: golang
    commands:
      - cd cmd
      - go test
  - name: publish
    image: golang
    commands:
      - cd cmd
      - go test