migrateup:
migrate -path db/migration -database "postgresql://<user>:<pwd>@localhost:5432/go_sample?sslmode=disable" -verbose up
migratedown:
migrate -path db/migration -database "postgresql://<user>@<pwd>:5432/go_sample?sslmode=disable" -verbose down
